version: "3.9"
    
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - .tmp/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_ROOT_PASSWORD: Pa$$w0rd!
      MYSQL_DATABASE: comblack
      MYSQL_USER: comblack
      MYSQL_PASSWORD: comblack

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    
  wordpress:
    depends_on:
      - db
    image: wordpress:6.0.0-php7.4-apache
    container_name: wp
    volumes:
      - .tmp/wordpress:/var/www/html
      - ./:/usr/original_src
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress/wp-content/plugins/careerist/logs:/var/www/html/wp-content/plugins/careerist/logs
    ports:
      - "8000:80"
    restart: always
    command: /usr/original_src/docker-entrypoint.sh /var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: comblack
      WORDPRESS_DB_PASSWORD: comblack
      WORDPRESS_DB_NAME: comblack
      WORDPRESS_DEBUG: 1
